# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addScansCPP <- function(iontable, scans) {
    .Call('_clams_addScansCPP', PACKAGE = 'clams', iontable, scans)
}

removeBackgroundCPP <- function(ionsTable, windowSize, aboveAverageMultiplier, minIntensity, mzRange) {
    .Call('_clams_removeBackgroundCPP', PACKAGE = 'clams', ionsTable, windowSize, aboveAverageMultiplier, minIntensity, mzRange)
}

groupIonsSameScanCPP <- function(ionsTable, mzTolerance) {
    .Call('_clams_groupIonsSameScanCPP', PACKAGE = 'clams', ionsTable, mzTolerance)
}

collectFinalPeaksCPP <- function(ionsDataFrame, mzTolerance, rtTolerance) {
    .Call('_clams_collectFinalPeaksCPP', PACKAGE = 'clams', ionsDataFrame, mzTolerance, rtTolerance)
}

sameMZCPP <- function(mzRange10, mzRange11, mzRange20, mzRange21, mzTolerance) {
    .Call('_clams_sameMZCPP', PACKAGE = 'clams', mzRange10, mzRange11, mzRange20, mzRange21, mzTolerance)
}

groupPeaksAcrossScansCPP <- function(ionsDataFrame, mzTolerance, rtTolerance, meanTimeBetweenScans) {
    .Call('_clams_groupPeaksAcrossScansCPP', PACKAGE = 'clams', ionsDataFrame, mzTolerance, rtTolerance, meanTimeBetweenScans)
}

